kind: pipeline
name: kaniko-test

platform:
  os: linux
  arch: arm

workspace:
  base: /go
#  path: src/github.com/GoogleContainerTools/kaniko

volumes:
- name: kaniko
  temp: {}

# get kaniko repository into /drone/
steps:
- name: clone-kaniko
  image: drone/git
  commands: 
  - git clone https://github.com/GoogleContainerTools/kaniko /go/src/github.com/GoogleContainerTools/kaniko

- name: build
  image: golang:1.10
  volumes:
  - name: kaniko
    path: /kaniko
  commands:
  - cd /go/src/github.com/GoogleContainerTools/kaniko
  - cp /go/kaniko-extra/Makefile Makefile
  - make out/executor
  - cp out/executor /kaniko
  - mkdir /kaniko/ssl
  - mkdir /kaniko/ssl/certs
  - cp files/ca-certificates.crt /kaniko/ssl/certs/ca-certificates.crt
  - mkdir /kaniko/.docker
  - cp /go/kaniko-extra/config.json /kaniko/.docker/config.json
  - cp /go/plugin.sh /kaniko/plugin.sh
  - chmod +rwx /kaniko/plugin.sh

- name: publish-with-created-binary
  image: busybox
  volumes:
  - name: kaniko
    path: /kaniko-files
  settings:
    registry: docker.artificialcreature.com    
    repo: drone-plugins/kaniko
    tags: ${DRONE_COMMIT_SHA}
    dockerfile: /go/Dockerfile
    alternate_executor_path: /kaniko-filez/executor
  #  cache: false
    log: debug
  #  insecure_registry: false
  #  insecure: false
  #  insecure_pull: false
  #  skip_tls_verify: false
  environment:
    HOME: /root
    USER: /root
    SSL_CERT_DIR: /kaniko-files/ssl/certs
    DOCKER_CONFIG: /kaniko-files/.docker/
  user: root
  commands:
  - cat /go/plugin.sh
  - sed -i 's:/kaniko/:/kaniko-files/:g' /go/plugin.sh
  - cat /go/plugin.sh
  - cd /
  - /go/plugin.sh

- name: publish-with-pushed-image
  image: docker-registry:5000/drone-plugins/kaniko:${DRONE_COMMIT_SHA}
  volumes:
  - name: kaniko
    path: /kaniko-files
  settings:
    registry: docker.artificialcreature.com
    repo: drone-plugins/kaniko
    tags: latest
    dockerfile: /go/Dockerfile
    # cache: false
    log: debug
    # insecure_registry: false
    # insecure: false
    # insecure_pull: false
    # skip_tls_verify: false