kind: pipeline
name: kaniko-test

platform:
  os: linux
  arch: arm

workspace:
  base: /go
#  path: src/github.com/GoogleContainerTools/kaniko

volumes:
- name: kaniko
  temp: {}

# get kaniko repository into /drone/
steps:
- name: clone-kaniko
  image: drone/git
  commands: 
  - git clone https://github.com/GoogleContainerTools/kaniko /go/src/github.com/GoogleContainerTools/kaniko

- name: build
  image: golang:1.10
  volumes:
  - name: kaniko
    path: /kaniko
  
  commands:
  - cd /go/src/github.com/GoogleContainerTools/kaniko
  - cp /go/kaniko-extra/Makefile Makefile
  - make out/executor
  - cp out/executor /kaniko
  - mkdir /kaniko/ssl
  - mkdir /kaniko/ssl/certs
  - cp files/ca-certificates.crt /kaniko/ssl/certs/ca-certificates.crt
  - mkdir /kaniko/.docker
  - cp /go/kaniko-extra/config.json /kaniko/.docker/config.json

- name: publish
  image: busybox
  volumes:
  - name: kaniko
    path: /kaniko
  settings:
    registry: docker-registry:5000
    repo: kaniko/executor
    tags: ${DRONE_COMMIT_SHA}
    dockerfile: /go/Dockerfile
    cache: false
    log: debug
    insecure_registry: true
    insecure: true
  commands:
  - cd /
  - /kaniko/plugin.sh 


# - name: publish
#   image: docker-registry:5000/drone-plugins/drone-kaniko
#   volumes:
#   - name: kaniko-files
#     path: /kaniko-files
#   settings:
#     registry: docker-registry:5000
#     repo: kaniko/executor
#     tags: ${DRONE_COMMIT_SHA}
#     dockerfile: /go/Dockerfile
#     cache: false
#     log: debug
#     insecure_registry: true
#     insecure: true