kind: pipeline
name: kaniko-test

platform:
  os: linux
  arch: arm

workspace:
  base: /go
#  path: src/github.com/GoogleContainerTools/kaniko

volumes:
- name: kaniko-files
  temp: {}

# get kaniko repository into /drone/
steps:
- name: clone-kaniko
  image: drone/git
  commands: 
  - git clone https://github.com/GoogleContainerTools/kaniko /go/src/github.com/GoogleContainerTools/kaniko

- name: build
  image: golang:1.10
  volumes:
  - name: kaniko-files
    path: /kaniko-files
  
  commands:
  - cd /go/src/github.com/GoogleContainerTools/kaniko
  - cp /go/kaniko-extra/Makefile Makefile
  - make out/executor
  - cp out/executor /kaniko-files
  - mkdir /kaniko-files/ssl
  - mkdir /kaniko-files/ssl/certs
  - cp /go/files/ca-certificates.crt /kaniko-files/ssl/certs/ca-certificates.crt
  - mkdir /kaniko-files/.docker
  - cp /go/deploy/config.json /kaniko-files/.docker/config.json

# # /var/cache/drone/src/$domain/$owner/$name


# - name: publish-drone-kaniko-plugin
#   image: docker-registry:5000/drone-plugins/drone-kaniko
#   settings:
#     registry: docker-registry:5000
#     repo: kaniko/executor
#     tags: ${DRONE_COMMIT_SHA}
#     dockerfile: Dockerfile
  
  # cache: true