kind: pipeline
name: kaniko-test

platform:
  os: linux
  arch: arm

workspace:
  base: /go
#  path: src/github.com/GoogleContainerTools/kaniko

volumes:
- name: kaniko
  temp: {}

# get kaniko repository into /drone/
steps:
- name: clone-kaniko
  image: drone/git
  commands: 
  - git clone https://github.com/GoogleContainerTools/kaniko /go/src/github.com/GoogleContainerTools/kaniko

- name: build
  image: golang:1.10
  # volumes:
  # - name: kaniko
  #   path: /kaniko
  commands:
  - cd /go/src/github.com/GoogleContainerTools/kaniko
  - cp /go/kaniko-extra/Makefile Makefile
  - make out/executor
  - mkdir /go/kaniko-files
  - cp out/executor /go/kaniko-files
  - mkdir /go/kaniko-files/ssl
  - mkdir /go/kaniko-files/ssl/certs
  - cp files/ca-certificates.crt /go/kaniko-files/ssl/certs/ca-certificates.crt
  - mkdir /go/kaniko-files/.docker
  - cp /go/kaniko-extra/config.json /go/kaniko-files/.docker/config.json
  - cp /go/plugin.sh /go/kaniko-files/plugin.sh
  - chmod +rwx /go/kaniko-files/plugin.sh

- name: publish-image
  image: arm32v7/busybox
  # volumes:
  # - name: kaniko
  #   path: /kaniko-files
  settings:
    registry: docker.artificialcreature.com    
    repo: drone-plugins/kaniko
    tags: ${DRONE_COMMIT_SHA}
#    dockerfile: /go/Dockerfile
    log: info
    kaniko_path: /go/kaniko-files
  environment:
    HOME: /root
    USER: /root
    SSL_CERT_DIR: /go/kaniko-files/ssl/certs
    DOCKER_CONFIG: /go/kaniko-files/.docker/
  user: root
  commands:
  - mkdir /kaniko
  - cp /go/kaniko-files/* /kaniko -R
 # - cd /
  - /go/kaniko-files/plugin.sh

- name: test-and-republish-image
  image: docker-registry:5000/drone-plugins/kaniko:${DRONE_COMMIT_SHA}
  # volumes:
  # - name: kaniko
  #   path: /go/kaniko-files
  settings:
    registry: docker.artificialcreature.com
    repo: drone-plugins/kaniko
    tags: latest
#    dockerfile: /go/Dockerfile
    log: info