kind: pipeline
name: kaniko-test

platform:
  os: linux
  arch: arm

workspace:
  base: /go
#  path: src/github.com/GoogleContainerTools/kaniko

volumes:
- name: kaniko
  temp: {}

# get kaniko repository into /drone/
steps:
- name: clone-kaniko
  image: drone/git
  commands: 
  - git clone https://github.com/GoogleContainerTools/kaniko /go/src/github.com/GoogleContainerTools/kaniko

- name: build
  image: golang:1.10
  volumes:
  - name: kaniko
    path: /kaniko
  commands:
  - cd /go/src/github.com/GoogleContainerTools/kaniko
  - cp /go/kaniko-extra/Makefile Makefile
  - make out/executor
  - cp out/executor /kaniko
  - mkdir /kaniko/ssl
  - mkdir /kaniko/ssl/certs
  - cp files/ca-certificates.crt /kaniko/ssl/certs/ca-certificates.crt
  - mkdir /kaniko/.docker
  - cp /go/kaniko-extra/config.json /kaniko/.docker/config.json
  - cp /go/plugin.sh /kaniko/plugin.sh
  - chmod +rwx /kaniko/plugin.sh


- name: publish-image
  image: arm32v7/busybox
  volumes:
  - name: kaniko
    path: /kaniko-files
  settings:
    registry: docker.artificialcreature.com    
    repo: drone-plugins/kaniko
    tags: ${DRONE_COMMIT_SHA}
    dockerfile: /go/Dockerfile
    log: info
    kaniko_path: /kaniko-files
  environment:
    HOME: /root
    USER: /root
    SSL_CERT_DIR: /kaniko-files/ssl/certs
    DOCKER_CONFIG: /kaniko-files/.docker/
  user: root
  commands:
  - mkdir /kaniko
  - cp /kaniko-files/* /kaniko -R
  - cd /
  - /kaniko-files/plugin.sh

- name: test-and-republish-image
  image: docker-registry:5000/drone-plugins/kaniko:${DRONE_COMMIT_SHA}
  volumes:
  - name: kaniko
    path: /kaniko-files
  settings:
    registry: docker.artificialcreature.com
    repo: drone-plugins/kaniko
    tags: latest
    dockerfile: /go/Dockerfile
#    kaniko_path: /kaniko
    log: debug